<?php

namespace Database\Seeders;

use App\Models\AttractionPrice;
use Illuminate\Database\Seeder;

class AttractionPriceSeeder extends Seeder
{
    public function run(): void
    {
        $attractions = [
            [
                'name' => 'Petronas Twin Towers',
                'state' => 'Kuala Lumpur',
                'aliases' => ['KLCC', 'Petronas Towers', 'Suria KLCC'],
                'category' => 'sightseeing',
                'price_myr' => 98.00,
                'price_label' => 'Adult (foreign) observation deck',
                'source_name' => 'Official PETRONAS Twin Towers',
                'source_url' => 'https://www.petronastwintowers.com.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Batu Caves',
                'state' => 'Selangor',
                'aliases' => ['Batu Caves Temple', 'Sri Subramaniar Temple'],
                'category' => 'sightseeing',
                'price_myr' => 0.00,
                'price_label' => 'Free entry (cave temple)',
                'source_name' => 'Tourism Selangor',
                'source_url' => 'https://www.selangor.travel',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Langkawi Sky Bridge',
                'state' => 'Kedah',
                'aliases' => ['Langkawi Cable Car', 'SkyCab Langkawi', 'Panorama Langkawi'],
                'category' => 'sightseeing',
                'price_myr' => 91.00,
                'price_label' => 'Standard combo ticket (reference)',
                'source_name' => 'Panorama Langkawi',
                'source_url' => 'https://www.panoramalangkawi.com',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Jonker Street Night Market',
                'state' => 'Melaka',
                'aliases' => ['Jonker Walk', 'Jonker Street'],
                'category' => 'food',
                'price_myr' => 30.00,
                'price_label' => 'Average food spend per person',
                'source_name' => 'Melaka State Tourism',
                'source_url' => 'https://www.melaka.gov.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'BOH Tea Plantation',
                'state' => 'Pahang',
                'aliases' => ['BOH Tea Estate', 'Cameron Highlands Tea Plantation'],
                'category' => 'sightseeing',
                'price_myr' => 0.00,
                'price_label' => 'Free factory tour',
                'source_name' => 'BOH Tea',
                'source_url' => 'https://www.boh.com.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'George Town UNESCO Heritage Walk',
                'state' => 'Penang',
                'aliases' => ['George Town Heritage', 'Penang Heritage Zone'],
                'category' => 'heritage',
                'price_myr' => 0.00,
                'price_label' => 'Self-guided walking (free)',
                'source_name' => 'Penang Global Tourism',
                'source_url' => 'https://www.visitpenang.gov.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Khoo Kongsi',
                'state' => 'Penang',
                'aliases' => ['Khoo Kongsi Clan House'],
                'category' => 'heritage',
                'price_myr' => 10.00,
                'price_label' => 'Adult entry',
                'source_name' => 'Khoo Kongsi Official',
                'source_url' => 'https://www.khookongsi.com.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Penang Hill Funicular',
                'state' => 'Penang',
                'aliases' => ['Penang Hill Railway', 'Bukit Bendera'],
                'category' => 'sightseeing',
                'price_myr' => 12.00,
                'price_label' => 'Adult return ticket (Malaysian)',
                'source_name' => 'Penang Hill Corporation',
                'source_url' => 'https://www.penanghill.gov.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Aquaria KLCC',
                'state' => 'Kuala Lumpur',
                'aliases' => ['KLCC Aquarium'],
                'category' => 'sightseeing',
                'price_myr' => 69.00,
                'price_label' => 'Adult entry',
                'source_name' => 'Aquaria KLCC',
                'source_url' => 'https://www.aquariaklcc.com',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Sunway Lagoon',
                'state' => 'Selangor',
                'aliases' => ['Sunway Theme Park'],
                'category' => 'sightseeing',
                'price_myr' => 188.00,
                'price_label' => 'Adult day pass (reference)',
                'source_name' => 'Sunway Lagoon Official',
                'source_url' => 'https://sunwaylagoon.com',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Kinabalu Park',
                'state' => 'Sabah',
                'aliases' => ['Mount Kinabalu Park', 'Taman Kinabalu'],
                'category' => 'nature',
                'price_myr' => 15.00,
                'price_label' => 'Malaysian adult entry fee',
                'source_name' => 'Sabah Parks',
                'source_url' => 'https://www.sabahparks.org.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Sepilok Orangutan Rehabilitation Centre',
                'state' => 'Sabah',
                'aliases' => ['Sepilok Orangutan Centre'],
                'category' => 'nature',
                'price_myr' => 30.00,
                'price_label' => 'Foreign adult entry',
                'source_name' => 'Sabah Wildlife Department',
                'source_url' => 'https://www.sabah.gov.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'A Famosa Fort',
                'state' => 'Melaka',
                'aliases' => ['Porta de Santiago', 'Melaka Fort'],
                'category' => 'heritage',
                'price_myr' => 0.00,
                'price_label' => 'Free entry (exterior)',
                'source_name' => 'Melaka State Tourism',
                'source_url' => 'https://www.melaka.gov.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Stadthuys Melaka',
                'state' => 'Melaka',
                'aliases' => ['Red Square Melaka', 'Dutch Square'],
                'category' => 'heritage',
                'price_myr' => 0.00,
                'price_label' => 'Free exterior visit',
                'source_name' => 'Melaka State Tourism',
                'source_url' => 'https://www.melaka.gov.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'National Museum of Malaysia',
                'state' => 'Kuala Lumpur',
                'aliases' => ['Muzium Negara'],
                'category' => 'heritage',
                'price_myr' => 5.00,
                'price_label' => 'Malaysian adult entry',
                'source_name' => 'Department of Museums Malaysia',
                'source_url' => 'https://www.jmm.gov.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Islamic Arts Museum Malaysia',
                'state' => 'Kuala Lumpur',
                'aliases' => ['IAMM'],
                'category' => 'heritage',
                'price_myr' => 20.00,
                'price_label' => 'Adult entry',
                'source_name' => 'Islamic Arts Museum Malaysia',
                'source_url' => 'https://www.iamm.org.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'The Habitat Penang Hill',
                'state' => 'Penang',
                'aliases' => ['Habitat Penang', 'Penang Hill Nature Walk'],
                'category' => 'nature',
                'price_myr' => 60.00,
                'price_label' => 'Adult standard entry',
                'source_name' => 'The Habitat Penang Hill',
                'source_url' => 'https://thehabitat.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Kek Lok Si Temple',
                'state' => 'Penang',
                'aliases' => ['Temple of Supreme Bliss'],
                'category' => 'heritage',
                'price_myr' => 6.00,
                'price_label' => 'Inclined lift return ticket',
                'source_name' => 'Penang Global Tourism',
                'source_url' => 'https://www.visitpenang.gov.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Cameron Highlands Strawberry Farm',
                'state' => 'Pahang',
                'aliases' => ['Big Red Strawberry Farm', 'Strawberry Farm Cameron'],
                'category' => 'nature',
                'price_myr' => 0.00,
                'price_label' => 'Free entry (pay for produce)',
                'source_name' => 'Cameron Highlands tourism reference',
                'source_url' => 'https://www.cameronhighlands.com',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Mossy Forest Cameron Highlands',
                'state' => 'Pahang',
                'aliases' => ['Cameron Mossy Forest', 'Boardwalk Mossy Forest'],
                'category' => 'nature',
                'price_myr' => 30.00,
                'price_label' => 'Guided tour reference price',
                'source_name' => 'Cameron Highlands tourism reference',
                'source_url' => 'https://www.cameronhighlands.com',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Underwater World Langkawi',
                'state' => 'Kedah',
                'aliases' => ['Langkawi Aquarium'],
                'category' => 'sightseeing',
                'price_myr' => 55.00,
                'price_label' => 'Adult entry (reference)',
                'source_name' => 'Underwater World Langkawi',
                'source_url' => 'https://www.underwaterworldlangkawi.com',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Kilim Geoforest Park',
                'state' => 'Kedah',
                'aliases' => ['Kilim Karst Geoforest Park', 'Langkawi Mangrove Tour'],
                'category' => 'nature',
                'price_myr' => 40.00,
                'price_label' => 'Boat tour reference price',
                'source_name' => 'Langkawi Development Authority',
                'source_url' => 'https://www.lada.gov.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Perhentian Islands Marine Park',
                'state' => 'Terengganu',
                'aliases' => ['Pulau Perhentian', 'Perhentian Snorkeling'],
                'category' => 'nature',
                'price_myr' => 30.00,
                'price_label' => 'Marine park conservation fee',
                'source_name' => 'Marine Parks Malaysia',
                'source_url' => 'https://www.dmpm.nre.gov.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Redang Island Marine Park',
                'state' => 'Terengganu',
                'aliases' => ['Pulau Redang'],
                'category' => 'nature',
                'price_myr' => 30.00,
                'price_label' => 'Marine park conservation fee',
                'source_name' => 'Marine Parks Malaysia',
                'source_url' => 'https://www.dmpm.nre.gov.my',
                'price_as_of' => '2026-01-01',
            ],
            [
                'name' => 'Central Market Kuala Lumpur',
                'state' => 'Kuala Lumpur',
                'aliases' => ['Pasar Seni', 'KL Central Market'],
                'category' => 'shopping',
                'price_myr' => 0.00,
                'price_label' => 'Free entry',
                'source_name' => 'Central Market Kuala Lumpur',
                'source_url' => 'https://www.centralmarket.com.my',
                'price_as_of' => '2026-01-01',
            ],
        ];

        foreach ($attractions as $attraction) {
            AttractionPrice::updateOrCreate(
                ['name' => $attraction['name'], 'state' => $attraction['state']],
                $attraction
            );
        }
    }
}
